### ISSUE TITLE
CM19?

### ISSUE THREAD

**Issue by darkzbaron** [jfhovinne/pycm15#2]
Have you had the chance to try with the CM19?Thanks, Jonathan

**Comment by jfhovinne** [comment]
No, the implementation is CM15 specific, while I do not have a CM19 device at my disposal to test with.
It should be possible to make the code more generic and be able to connect to a e.g. a CM19, but that is not the original purpose of this (small) project.

**Comment by darkzbaron** [comment]
Hi Jean Francois,

Merci for the feedback! I am trying to find a solution for my RPI and it looks like i will probably get a CM15 because it has more possibility and code available. Any experience with a RPI?

Thanks again. Jonathan

**Comment by jfhovinne** [comment]
Did not try with my RPIs yet, but as soon as dependencies are available (see readme), should be fine.
Make sure you use PyUSB 0.x (since 1.x API is different), which should be the case in Raspbian.

**Comment by darkzbaron** [comment]
ok cool. Thanks so much for your help!

**Comment by jfhovinne** [comment]
You are welcome, as well as your feedback on using pycm15!
Happy hacking :)

**Comment by darkzbaron** [comment]
Thanks! Really appreciate !                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Jean-François HovinneSent: Wednesday, 8 March 2017 20:24To: jfhovinne/pycm15Reply To: jfhovinne/pycm15Cc: darkzbaron; State changeSubject: Re: [jfhovinne/pycm15] CM19? (#2)You are welcome, as well as your feedback on using pycm15!
Happy hacking :)

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jfhovinne/pycm15","title":"jfhovinne/pycm15","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jfhovinne/pycm15"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jfhovinne in #2: You are welcome, as well as your feedback on using pycm15!\r\nHappy hacking :)"}],"action":{"name":"View Issue","url":"https://github.com/jfhovinne/pycm15/issues/2#issuecomment-285141332"}}}
