### ISSUE TITLE
10 to 16 do not work

### ISSUE THREAD

**Issue by hanssipi** [jfhovinne/pycm15#3]
Hello,
I tried your code and it works fine except for the commands 10 to 16.
A1 to A9 works, but A10 to A16 not. (cm15send.py A10 ON) --> Incorrect X10 address
Am i doing something wrong? Thanks!

Never mind, found a solution.

**Comment by jfhovinne** [comment]
Hello @hanssipi 
Bug fix committed; would be great if you could confirm it fixes your issue.

**Comment by hanssipi** [comment]
Hello jfhovinne,
Thanks for the fix, it works great now!
